// components/Layout.jsx
import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Navbar from "@/components/Navbar";
import { Inter } from "@next/font/google";



const Layout = ({ title, children }) => {
    const inter = Inter({ subsets: ["latin"] });
    const interStyles = inter.getStyleElement();

    return (
        <>
            <Head>
                <title>{title}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
                {interStyles}
            </Head>
            <main className={`${styles.main} ${inter.className}`}>
                <div>
                    <Navbar />
                </div>
                <div>
                    {children}
                </div>
            </main>
        </>
    );
};

export default Layout;
