import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";
import { useState} from 'react';

const inter = Inter({ subsets: ["latin"] });
export default function Home() {
    const [counter, setCounter] = useState(4);
      //useState(0) indicates counter starting point
      const handleClick = () => {
        setCounter(counter + 1);
      };
      const minusClick = () => {
        setCounter(counter - 1);
      };

  return (
    <>
      <Head>
        <title>Vanilla Celebration Cake</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
      <div>
          <nav>
            <ul className="navbarUl">
              <li className="navbarLi">
                <Link href="index" className="navbara"> Home</Link>
              </li>
              <li className="navbarLi">
                <Link href="index" className="navbara" >A-Z Recipes</Link>
              </li>
              <li className="navbarLi">
                <Link href="index" className="navbara" >Gallery</Link>
              </li>
            </ul>
          </nav>
        </div>
        <div>
          <h2 className="recipePageTitle">Millionaires Shortbread</h2>
          <img src="millionairesshortbread.jpg" /> 
          <p className="recipeSummary">Easy to make but setting time needed. Versatile decoration options including feathering or drizzling chocolate, or a theme decor. I also make these with no biscuit base - just caramel and chocolate, then flip over and do chocolate on the bottom as well. </p>
          <h3 className="numServings">Serves a lot</h3>
          <h4 className="ingredTitle">Ingredients:</h4>
          <h5 className="recipeStep">Base</h5>
          <ul className = "ingredList">
            <li>1</li>
          </ul>
          <h5 className="recipeStep">Caramel</h5>
          <ul className = "ingredList">
            <li>1</li>
          </ul>
          <h5 className="recipeStep">Chocolate top</h5>
          <ul className = "ingredList">
            <li>1</li>
          </ul>
          <h4 className="ingredTitle">Recipe:</h4>
          <h5 className="recipeStep">Base</h5>
          <ul className = "ingredList">
            <li>1</li>
          </ul>
          <h5 className="recipeStep">Caramel</h5>
          <ul className = "ingredList">
            <li>1</li>
          </ul>
          <h5 className="recipeStep">Chocolate top</h5>
          <ul className = "ingredList">
            <li>1</li>
          </ul>
          <h4 className="ingredTitle">Extra Notes:</h4>
          <ul className = "ingredList">
            <li>1</li>
          </ul>
        </div>
      </main>
    </>
  );
}
