import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";
import { useState} from 'react';

const inter = Inter({ subsets: ["latin"] });
export default function Home() {
    const [counter, setCounter] = useState(3);
      //useState(0) indicates counter starting point
      const handleClick = () => {
        setCounter(counter + 1);
      };
      const minusClick = () => {
        setCounter(counter - 1);
      };

  return (
    <>
      <Head>
        <title>Vanilla Celebration Cake</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
      <div>
          <nav>
            <ul className="navbarUl">
              <li className="navbarLi">
                <Link href="index" className="navbara"> Home</Link>
              </li>
              <li className="navbarLi">
                <Link href="index" className="navbara" >A-Z Recipes</Link>
              </li>
              <li className="navbarLi">
                <Link href="index" className="navbara" >Gallery</Link>
              </li>
            </ul>
          </nav>
        </div>
        <div>
          <h2 className="recipePageTitle">Vanilla Celebration Cake</h2>
          <img src="celebrationcake.jpg" /> 
          <p className="recipeSummary">I made this big boy for Nicola and Mark's engagement July 2023! Suitable for a celebration where you have lots of guests.</p>
          <h3 className="numServings">{counter} layer cake</h3>
          <button onClick={handleClick} className="servings">Add a layer</button>
          <button onClick={minusClick} className="servings">Minus a layer</button>
          <h4 className="ingredTitle">Ingredients:</h4>
          <h5 className="recipeStep">Cake</h5>
          <ul className = "ingredList">
            <li>{125*counter}g unsalted butter</li>
            <li>{125*counter}g caster sugar</li>
            <li>{2.5*counter} medium eggs</li>
            <li>{0.5*counter} tsp vanilla extract</li>
          </ul>
          <h5 className="recipeStep">Icing</h5>
          <ul className = "ingredList">
            <li></li>
          </ul>
          <h4 className="ingredTitle">Recipe:</h4>
          <h5 className="recipeStep">Cake</h5>
          <ul className = "ingredList">
            <li>Preheat your oven to 180C/160C fan and line {counter} 8"/20cm tins with parchment paper, and leave to the side. </li>
            <li>Beat together your butter and sugar for 3-4 minutes until light and fluffy. Try not to over beat.</li>
            <li>Split the cake mix between the two tins. I weigh it to make sure its even - each mix should weigh {250*counter}g each, roughly.</li>
            <li>Once in the tins, bake in the oven for 30-35 minutes, or until baked through. I check my cake is baked by using a skewer, and listening carefully to see if it bubbles.</li>
            <li>Once baked, leave to cool in the tin for 10 minutes, and then transfer to a wire rack to finish cooling. </li>
          </ul>
          <h5 className="recipeStep">Icing</h5>
          <ul className = "ingredList">
            <li>Make sure the butter is at room temperature when starting to make the buttercream.</li>
            <li>Beat the butter on its own for 10 minutes using the paddle attachment. Beating it for so long helps makes the color whiter rather than yellow-y.</li>
            <li>Add the icing sugar in 1/2 at a time, and beat fully before adding any more in. </li>
            <li>Add in the vanilla and beat again for 3-4 minutes.</li>
            <li>Pipe or spread buttercream onto the first layer of cake, and top with some jam.</li>
            <li>Add the next sponge, and repeat until you're on the last layer.</li>
            <li>Do a crumb coat around the whole cake and then put in the fridge to chill. Crumb coat layer doesn't have to be too thick.</li>
            <li>Once chilled and not sticky you can do the next layer of icing, smoothing it all around.</li>
            <li>Decorate however you wish!</li>          
          </ul>
          <h4 className="ingredTitle">Extra Notes:</h4>
          <ul className = "ingredList">
            <li>You could make less buttercream and have a 'naked' cake. Equally this looks quite nice as a semi-naked cake where you do basically just the crumb coat.</li>
            <li>I decorated Nicola and Mark's cake with forest fruits and mint leaves.</li>
            <li>Cake lasts 3 days at room temperature in a box.</li>
          </ul>
        </div>
      </main>
    </>
  );
}
